# 账号
mobile: "13300000000"
# 密码
password: "@@@chuanyueb29c71bfcc4dcbd18b97a0830c3afd34"
# 测试环境配置
test_url: "http://192.168.110.13:18006/"
# idcard_image图片
idcard_image: "http://berry.dev.uplasm.com/file/tests/demo.jpg"