# 账号
mobile: "13300000000"
# 密码
password: "@@@chuanyueb29c71bfcc4dcbd18b97a0830c3afd34"
# 培训环境配置
test_url: "https://plasma.sharing8.cn/"
# idcard_image图片
idcard_image: "http://berry.dev.uplasm.com/file/tests/demo.jpg"